var annotated_dup =
[
    [ "Board", "class_board.html", "class_board" ],
    [ "DiamondTicTacToe_Board", "class_diamond_tic_tac_toe___board.html", "class_diamond_tic_tac_toe___board" ],
    [ "DiamondTicTacToe_UI", "class_diamond_tic_tac_toe___u_i.html", "class_diamond_tic_tac_toe___u_i" ],
    [ "FivexFive_TicTacToe_Board", "class_fivex_five___tic_tac_toe___board.html", "class_fivex_five___tic_tac_toe___board" ],
    [ "FivexFive_TicTacToe_UI", "class_fivex_five___tic_tac_toe___u_i.html", "class_fivex_five___tic_tac_toe___u_i" ],
    [ "FourInRow_Board", "class_four_in_row___board.html", "class_four_in_row___board" ],
    [ "FourInRow_UI", "class_four_in_row___u_i.html", "class_four_in_row___u_i" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "Infinity_TicTacToe_Board", "class_infinity___tic_tac_toe___board.html", "class_infinity___tic_tac_toe___board" ],
    [ "Infinity_TicTacToe_UI", "class_infinity___tic_tac_toe___u_i.html", "class_infinity___tic_tac_toe___u_i" ],
    [ "MemoryTicTacToe_Board", "class_memory_tic_tac_toe___board.html", "class_memory_tic_tac_toe___board" ],
    [ "MemoryTicTacToe_UI", "class_memory_tic_tac_toe___u_i.html", "class_memory_tic_tac_toe___u_i" ],
    [ "Misere_TicTacToe_Board", "class_misere___tic_tac_toe___board.html", "class_misere___tic_tac_toe___board" ],
    [ "Misere_TicTacToe_UI", "class_misere___tic_tac_toe___u_i.html", "class_misere___tic_tac_toe___u_i" ],
    [ "Move", "class_move.html", "class_move" ],
    [ "Moving_XO_Board", "class_moving___x_o___board.html", "class_moving___x_o___board" ],
    [ "Moving_XO_UI", "class_moving___x_o___u_i.html", "class_moving___x_o___u_i" ],
    [ "Numerical_TicTacToe_Board", "class_numerical___tic_tac_toe___board.html", "class_numerical___tic_tac_toe___board" ],
    [ "Numerical_TicTacToe_UI", "class_numerical___tic_tac_toe___u_i.html", "class_numerical___tic_tac_toe___u_i" ],
    [ "Obstacles_TicTacToe_Board", "class_obstacles___tic_tac_toe___board.html", "class_obstacles___tic_tac_toe___board" ],
    [ "Obstacles_TicTacToe_UI", "class_obstacles___tic_tac_toe___u_i.html", "class_obstacles___tic_tac_toe___u_i" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "PyramidTicTacToe_Board", "class_pyramid_tic_tac_toe___board.html", "class_pyramid_tic_tac_toe___board" ],
    [ "PyramidTicTacToe_UI", "class_pyramid_tic_tac_toe___u_i.html", "class_pyramid_tic_tac_toe___u_i" ],
    [ "SUS_Board", "class_s_u_s___board.html", "class_s_u_s___board" ],
    [ "SUS_UI", "class_s_u_s___u_i.html", "class_s_u_s___u_i" ],
    [ "UI", "class_u_i.html", "class_u_i" ],
    [ "UltimateTicTacToe_Board", "class_ultimate_tic_tac_toe___board.html", "class_ultimate_tic_tac_toe___board" ],
    [ "UltimateTicTacToe_UI", "class_ultimate_tic_tac_toe___u_i.html", "class_ultimate_tic_tac_toe___u_i" ],
    [ "Word_TicTacToe_Board", "class_word___tic_tac_toe___board.html", "class_word___tic_tac_toe___board" ],
    [ "Word_TicTacToe_UI", "class_word___tic_tac_toe___u_i.html", "class_word___tic_tac_toe___u_i" ],
    [ "X_O_Board", "class_x___o___board.html", "class_x___o___board" ],
    [ "XO_UI", "class_x_o___u_i.html", "class_x_o___u_i" ]
];